### ISSUE TITLE
typo in readthedocs

### ISSUE THREAD

**Issue by amayer21** [cgat-developers/cgat-showcase#19]
There is a typo in the commands on the readthedocs page (https://cgat-showcase.readthedocs.io/en/latest/getting_started/Tutorial.html):

it should be `transdiffexprs` and not  `transdiffexpres` 

There are 3 occurences of it in 3 different commands (the 4th one has the right spelling)

This mistake has been corrected in the  cgat-showcase/docs/getting_started/Tutorial.rst file on GitHub

**Comment by Acribbs** [comment]
yes thanks, I have fixed this. Thanks for looking at it. Please let me know if you spot any other mistakes. Thanks.
