### ISSUE TITLE
problem import CGAT module in pipeline_transdiffexprs.py

### ISSUE THREAD

**Issue by amayer21** [cgat-developers/cgat-showcase#20]
First time I tried to run ```cgatshowcase transdiffexprs --help```, I had the following error message: 
`File "/home/u/u230707/cgat-install/conda-install/envs/cgat-c/lib/python3.6/site-packages/cgatshowcase/pipeline_transdiffexprs.py", line 114, in <module>
    import cgat.GTF as GTF 
ModuleNotFoundError: No module named 'cgat'`. 

While looking for the module, in cgat-c/lib/python3.6/site-packages, I found a folder called "CGAT" (in capital letters) with a GTF.py file in it, so I guessed the module need to be spelled with upper case... I changed it in the `pipeline_transdiffexprs.py` file (line 114) and ran the command again. The previous error message didn't come back so I guess it was the right thing to do (I have now another error message though, so I may be wrong).

**Comment by Acribbs** [comment]
hmm, did you install by running in a clean conda environment:
i.e. `conda env create -n cgatshowcase`?

Can you post the output of 
```
conda list cgat
```

Thanks

**Comment by amayer21** [comment]
I installed it in the cgat-c environment with
`conda install -c cgat cgatshowcase`

I followed the instructions from the readthedocs page of cgatcore "running a pipeline tutorial" (following the links)...

Here is the output of `conda list cgat`
```
# packages in environment at /home/u/u230707/cgat-install/conda-install/envs/cgat-c:
#
# Name                    Version                   Build  Channel
cgat-scripts              0.3.2            py36h355e19c_2    bioconda
cgatcore                  0.5.4                    py36_0    bioconda
cgatcore                  0.5.4                     <pip>
cgatshowcase              0.1.5           py36r341h14c3975_1    cgat
```

**Comment by Acribbs** [comment]
Ah you have two cgatcores. Could you type `which cgatcore` and `which cgat`

**Comment by Acribbs** [comment]
I think the issue could be due to two cgatcores, one that was installed using pip and another installed using conda. Does this jog any memories about how you installed cgatcore? I would personally install from scratch again on a clean environment

**Comment by Acribbs** [comment]
Actually, re-reading this I suspect that this is due to a cgat-scripts issue with the environment and could be linked to PYTHONPATH issues. I have actually removed the import cgat.GTF as it wasn't used anywhere in the pipeline anyway. I am currentrlky building a new conda environment with cgat-apps rather than cgat-scripts, whcih is a learner environment

**Comment by amayer21** [comment]
I started by installing cgatcore with `bash install-CGAT-tools.sh --devel` as described on the cgat-core's README on the github page (but with the error message described earlier). Then I did 
```
source </full/path/to/folder/without/trailing/slash>/conda-install/etc/profile.d/conda.sh
conda activate base
conda activate cgat-c
```
I think at that point I had only the pip one.

I then installed cgat-showcase with `conda install -c cgat cgatshowcase`. I think I had to add bioconda and conda-forge channels first for the command to work. The second cgatcore comes from that installation. I can read (amongst other):
```
The following NEW packages will be INSTALLED:
cgatcore:                          0.5.4-py36_0                          bioconda
```

I was somehow using cgatshow as a test for my cgatcore installation... as suggested by the tutorial page of cgatcore (https://cgat-core.readthedocs.io/en/latest/getting_started/Tutorial.html) which seems to say you should install cgatcore before to install cgatshow (but from your answers today I understand that it's not true, isn't it?)

When will your new conda environment be available?

**Comment by Acribbs** [comment]
Its available now on the cgat channel, im currently testing the installation and I will then build it for OSX. I am working on modifying the documentation, previously we didn't have a conda envuironment for this but now we do.

**Comment by amayer21** [comment]
I've started everything from scratch (from installation of miniconda), created an environment for cgatshowcase, activated it and installed cgatshowcase, but I still have the same error message as last time:
```
(cgatshowcase) u230707@genetic.master01 ~/nobackup/showcase/showcase_test_data $ cgatshowcase transdiffexprs config
Traceback (most recent call last):
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/bin/cgatshowcase", line 11, in <module>
    load_entry_point('cgatshowcase==0.1.8.1', 'console_scripts', 'cgatshowcase')()
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/cgatshowcase/entry.py", line 89, in main
    module = imp.load_module(pipeline, file, pathname, description)
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/cgatshowcase/pipeline_transdiffexprs.py", line 116, in <module>
    from cgatcore import pipeline as P
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/cgatcore/pipeline/__init__.py", line 327, in <module>
    from cgatcore.pipeline.control import *
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/cgatcore/pipeline/control.py", line 40, in <module>
    import drmaa
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/drmaa/__init__.py", line 63, in <module>
    from .session import JobInfo, JobTemplate, Session
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/drmaa/session.py", line 39, in <module>
    from drmaa.helpers import (adapt_rusage, Attribute, attribute_names_iterator,
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/drmaa/helpers.py", line 36, in <module>
    from drmaa.wrappers import (drmaa_attr_names_t, drmaa_attr_values_t,
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/drmaa/wrappers.py", line 56, in <module>
    _lib = CDLL(libpath, mode=RTLD_GLOBAL)
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /cm/shared/apps/torque/current/lib/libdrmaa.so.0: undefined symbol: _Z19drmaa_attrib_lookupPKcj
```

This time `conda list cgat` gives:
```
# packages in environment at /home/u/u230707/miniconda3/envs/cgatshowcase:
#
# Name                    Version                   Build  Channel
cgat-apps                 0.5.3            py36hc40942e_0    bioconda
cgatcore                  0.5.4                    py36_0    bioconda
cgatshowcase              0.1.8.1         py36r341h14c3975_1    cgat
```

**Comment by amayer21** [comment]
I tried to google but can't understand any of the results (both coming from issues raised in 2014):
https://github.com/cBio/cbio-cluster/issues/168
https://github.com/pygridtools/drmaa-python/issues/18

**Comment by Acribbs** [comment]
Ah this seems to be an issue with the python-drmaa and your torque cluster. The only version in conda is 0.7.6 and this was created at the beginning of 2014. In one of the references someone states  that torque v5 conda doesn't work. The python-drmaa is now 0.7.9 and i suspect this may fix it. I will try building a conda environment for 0.7.9 in the cgat channel and if im successful ask you to test it. Im not sure when I will get around this though. 

can you run `cgatshowcase transdiffexprs config --co-cluster` in the meantime?

**Comment by amayer21** [comment]
Thank you very much!
I just tried and it gave the same error (I also tried with `--no-cluster` instead of `--co-cluster`)...
```
Traceback (most recent call last):
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/bin/cgatshowcase", line 11, in <module>
    load_entry_point('cgatshowcase==0.1.8.1', 'console_scripts', 'cgatshowcase')()
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/cgatshowcase/entry.py", line 89, in main
    module = imp.load_module(pipeline, file, pathname, description)
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/cgatshowcase/pipeline_transdiffexprs.py", line 116, in <module>
    from cgatcore import pipeline as P
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/cgatcore/pipeline/__init__.py", line 327, in <module>
    from cgatcore.pipeline.control import *
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/cgatcore/pipeline/control.py", line 40, in <module>
    import drmaa
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/drmaa/__init__.py", line 63, in <module>
    from .session import JobInfo, JobTemplate, Session
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/drmaa/session.py", line 39, in <module>
    from drmaa.helpers import (adapt_rusage, Attribute, attribute_names_iterator,
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/drmaa/helpers.py", line 36, in <module>
    from drmaa.wrappers import (drmaa_attr_names_t, drmaa_attr_values_t,
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/site-packages/drmaa/wrappers.py", line 56, in <module>
    _lib = CDLL(libpath, mode=RTLD_GLOBAL)
  File "/home/u/u230707/miniconda3/envs/cgatshowcase/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /cm/shared/apps/torque/current/lib/libdrmaa.so.0: undefined symbol: _Z19drmaa_attrib_lookupPKcj
```

**Comment by Acribbs** [comment]
Hi,

I have built a new version of python-drmaa and added it to the cgat channel. Are you able to test it by running:

```
conda uninstall python-drmaa
conda install -c cgat python-drmaa
```

Then try running a pipeine

**Comment by amayer21** [comment]
Thanks Adam, I will try that now. just to be sure to understand correctly: I need to activate cgatshow environment, then run your 2 commands inside that environment? I don't need to rebuild the whole environment, do I?

End of last week I've also installed cgatshow on my computer to test it without drmaa. The first attempt didn't work because the `import cgat.GTF as GTF` line was still in the pipeline code I downloaded with conda (despite the fact that you remove that line from the same script on GitHub). I removed the line and it then worked. I ran transdiffexprs on the test data and it went smoothly. However I noticed a few other changes on the GitHub that were not changed in the conda version (for exemple I don't have the line 117 `import cgatshowcase.ModuleTransdiffexprs as ModuleTransdiffexprs`). Do I need to do something to update it?

**Comment by Acribbs** [comment]
Hi,

yes activate the cgatshowcase environment then run those commands. 

Unfortunately I realised that particular conda environment for showcase was packaged incorrectly and pointed to a bug. To fix the import GTF error you will need setup the showcase installation again.

These are the steps you will need to take to make the showcase work properly:

```
mv <to a folder you want to install cgatshowcase>
git clone git@github.com:cgat-developers/cgat-showcase.git
cd cgat-showcase
python setup.py develop

```

This should now have the latest environment installed in your chatsgowcase envrionment, without the bug

**Comment by amayer21** [comment]
I have lots of questions (sorry) but will try to go one by one...
I've first tried to uninstall and re-install python-drmaa but I guess I've done a mistake...
When I ran `conda uninstall python-drmaa`, it said:
```
## Package Plan ##

  environment location: /home/u/u230707/miniconda3/envs/cgatshowcase

  removed specs: 
    - python-drmaa


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2p             |    h14c3975_1002         3.1 MB  conda-forge

The following packages will be REMOVED:

    cgat-apps:    0.5.3-py36hc40942e_0       bioconda   
    cgatcore:     0.5.4-py36_0               bioconda   
    cgatshowcase: 0.1.8.1-py36r341h14c3975_1 cgat       
    python-drmaa: 0.7.6-py36_0               conda-forge

The following packages will be UPDATED:

    openssl:      1.0.2p-h470a237_2          conda-forge --> 1.0.2p-h14c3975_1002 conda-forge

Proceed ([y]/n)?
```
and I replied `yes`... but when I then did `conda install -c cgat python-drmaa`, it installed only python-drmaa:
```
## Package Plan ##

  environment location: /home/u/u230707/miniconda3/envs/cgatshowcase

  added / updated specs: 
    - python-drmaa


The following NEW packages will be INSTALLED:

    python-drmaa: 0.7.6-py36_0 conda-forge

Proceed ([y]/n)? y
```
 so it can't find the command cgatshowcase anymore :-( 
```
(cgatshowcase) u230707@genetic.master01 ~ $ cgatshowcase transdiffexprs --help
-bash: cgatshowcase: command not found
```

I guess I have to re-install cgatshowcase, cgat-apps and cgatcore...

**Comment by amayer21** [comment]
I've reinstall cgatshowcase, cgat-apps and cgatcore, then tried `cgatshowcase transdiffexprs --help` but ended up with the same error message as previously (finishing by: `OSError: /cm/shared/apps/torque/current/lib/libdrmaa.so.0: undefined symbol: _Z19drmaa_attrib_lookupPKcj`)...

But then when looking at my prvious comment, I noticed that despite the fact I specified the cgat channel in `conda install -c cgat python-drmaa`, the one it installed is exactly the same as the one I uninstalled (from conda-forge: `python-drmaa: 0.7.6-py36_0 conda-forge`)

Is that how it should be? Did I do something wrong?

**Comment by Acribbs** [comment]
Ah this is most likely because the installations are pinned to version 0.7.6. Hmm, I will need to think about this. Can you install cgat-showcase on a separate environment by running:

```
conda env create cgat/cgatshowcase-env
conda activate cgatshowcase-env

conda uninstall python-drmaa. <click yes, this will likely uninstall cgat-showcase>
conda install -c cgat python-drmaa=0.7.9

```

Then you can install cgat-showcase using pip:

```
pip install cgatshowcase
```

To fix this I think that I may need to release (or get the developers to release) a new version of python-drmaa to the conda forge channel.

**Comment by amayer21** [comment]
I tried `conda env create cgat/cgatshowcase-env` and had the following error message:
```
SpecNotFound: Anaconda Client is required to interact with anaconda.org or an Anaconda API. Please run `conda install anaconda-client`.
```

I ran `conda install anaconda-client` without any problem, then tried the first command again but ended up with the same error message...

**Comment by amayer21** [comment]
I've also tried the same on my computer. I also had to install anaconda-client. Then I ran `conda env create cgat/cgatshowcase-env` again and ended up with the following message:
```
WARNING: Binstar environments are deprecated and scheduled to be removed in conda 4.5. See conda issue #5843 at https://github.com/conda/conda/pull/5843 for more information.
Solving environment: failed

ResolvePackageNotFound: 
  - gettext==0.19.8.1=h5e8e0c9_1
  - numpy==1.12.1=py36he24570b_1
  - libgcc==7.2.0=h69d50b8_2
  - xorg-libsm==1.2.3=h8c8a85c_0
  - wget==1.19.5=h1ad7b7a_0
  - bedtools==2.27.1=he941832_2
  - gstreamer==1.12.5=h61a6719_0
  - graphite2==1.3.13=hfc679d8_0
  - gst-plugins-base==1.12.5=hde13a9d_0
  - libstdcxx-ng==7.2.0=hdf63c60_3
  - cgatshowcase==0.1.8.2=py36r341h14c3975_1
  - libgfortran-ng==7.2.0=hdf63c60_3
  - scipy==1.1.0=py36hc49cb51_0
  - qt==5.6.2=7
  - libgcc-ng==8.2.0=hdf63c60_1
```
I guess on the server it doesn't work because the anaconda-client doesn't work (probably not allowed?). On my computer I don't have any idea why it's not working...

**Comment by Acribbs** [comment]
This is because the environment is only for a linux environment. OSX doesn't have a number of those packages. Particularly the libgcc-ng e.c.t.

I have no idea why the anaconda-client isn't being picked up. 

Can you run `conda list anaconda-client`

Did you specify the anaconda channel? It could be a badly packaged environment: run `conda install -c anaconda anaconda-client`

Can you also show me the output of `less ~/.condarc`

**Comment by amayer21** [comment]
```
(cgatshowcase) u230707@genetic.master01 ~ $ conda list anaconda-client
# packages in environment at /home/u/u230707/miniconda3/envs/cgatshowcase:
#
# Name                    Version                   Build  Channel
anaconda-client           1.7.1                      py_0    conda-forge
```
It looks like it's there... do I need to install it in the `base` environment instead ?

And `less ~/.condarc` gave:
```
channels:
  - bioconda
  - conda-forge
  - defaults
/home/u/u230707/.condarc (END)
```

**Comment by amayer21** [comment]
In the meantime, I've created the environment with `conda create -n cgatshowcase-env -c cgat cgatshowcase`, activated it, uninstalled python-drmaa and tried to install version 7.9 with `conda install -c cgat python-drmaa=0.7.9`. It took ages and still gave the following error message:
```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python-drmaa=0.7.9
  - spectra
Use "conda info <package>" to see the dependencies for each package.
```

When typing `conda info python-drmaa` it doesn't give any info on any version higher than 0.7.6... 

`conda list spectra` gave 
```
# packages in environment at /home/u/u230707/miniconda3/envs/cgatshowcase-env:
#
# Name                    Version                   Build  Channel
spectra                   0.0.11                     py_0    conda-forge
```
and the info about this package are
```
spectra 0.0.11 py_0
-------------------
file name   : spectra-0.0.11-py_0.tar.bz2
name        : spectra
version     : 0.0.11
build string: py_0
build number: 0
channel     : https://conda.anaconda.org/conda-forge/noarch
size        : 18 KB
arch        : None
constrains  : ()
license     : MIT
license_family: MIT
md5         : 87771d36053cb064308aec6a4135bcfa
noarch      : python
platform    : None
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/spectra-0.0.11-py_0.tar.bz2
dependencies:
    colormath ==3.0.0
    networkx ==2.0
    python
```
Not sure why it could be in conflict with python-drmaa 0.7.9 

Happy to try again with the anaconda channel tomorrow if it has a chance to have a different outcome...

I'm also planning to try to write a small pipeline myself with cgatcore and see if I can run it (I actually don't need cgatshow for the moment, I was trying it as a test of cgatcore)... but I guess I'll end up with the same problem with drmaa when I'll try to run my pipeline on the server...

**Comment by amayer21** [comment]
In parrallel, I've also tried to clone the repository on my computer (to have the last version of the pipeline as discussed before) with `git clone git@github.com:cgat-developers/cgat-showcase.git` but it didn't work:
```
git clone git@github.com:cgat-developers/cgat-showcase.git
Cloning into 'cgat-showcase'...
Warning: Permanently added the RSA host key for IP address '140.82.118.3' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

As I said, I don't really need cgatshowcase, so don't actually need to solve this problem... but if there is something I did wrong and I should learn to avoid doing it wrong again in the future, please let me know (and I apologise if it's trivial).

Thank you very much for your help!!!!

**Comment by Acribbs** [comment]
This is because you should use a http link not a ssh (you probably dont have your ssh keys set up), there is a green button to change to https when you clone the link from GitHub.

Given that the showcase is pinned what you probably need to do is just install cgatcore and cgat-apps in a separate environment the you can build your own pipelines using this.

However, in your case you will need to install python-drmaa from cgat channel. Then install other dependancies as and when you need them.

In the meantime I will have a look at the installation of cgatshowcase and remove the pinning for python-drmma, I may ask you to test it in the future if thats ok?

**Comment by amayer21** [comment]
That makes sense, thanks! 

Hopefully the python-drmaa is not pinned in cgatcore. 

Happy to test the new installation of cgatshowcase whenever needed!

Thank you very much for your help!

**Comment by Acribbs** [comment]
So the reason for python-drmaa failing was that it automatically set the python requirements for being > python=3.6. I have repackaged the python-drmaa and it should now work for both showcase and installing cgat-apps then cgatcore. 

Will close but reopen if there is still an issue
